<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="first.css"?>


<!DOCTYPE catalog [
    
    <!ELEMENT product (name,characteristica,temperatura,cost)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT characteristica (#PCDATA)>
    <!ELEMENT temperatura (#PCDATA)>
    <!ELEMENT cost (#PCDATA)>
    <!ENTITY c "Цена(₽):">
]>
<catalog>
    <product>

        <name>Intel Core i9−14900K</name>

        <characteristica>Техпроцесс(нм): 10</characteristica>
        
        <temperatura>Тепловыделение(Вт): 125</temperatura>

        <cost>&c; 100 000 </cost>

    </product>
    <product>

        <name>AMD Ryzen 9 7950X3D</name>

        <characteristica>Техпроцесс(нм): 5</characteristica>
        
        <temperatura>Тепловыделение(Вт): 170</temperatura>

        <cost>&c; 74 000</cost>

    </product>    
    <product>

        <name>AMD Ryzen 7 5800X3D</name>

        <characteristica>Техпроцесс(нм): 7</characteristica>
        
        <temperatura>Тепловыделение(Вт): 105</temperatura>

        <cost>&c; 37 000</cost>

    </product>    
    <product>

        <name>Intel Core i7−14700K</name>

        <characteristica>Техпроцесс(нм): 10</characteristica>
        
        <temperatura>Тепловыделение(Вт): 125</temperatura>

        <cost>&c; 66 000</cost>

    </product>    
    <product>

        <name>AMD Ryzen 5 5600X</name>

        <characteristica>Техпроцесс(нм): 7</characteristica>
        
        <temperatura>Тепловыделение(Вт): 65</temperatura>

        <cost>&c; 17 000</cost>

    </product>    
</catalog>